### ISSUE TITLE
efisiglist compile error

### ISSUE THREAD

**Issue by Doncuppjr** [rhinstaller/pesign#12]
During compilation, I get the following error, that I am unable to resolve on my own. I did note that you made a fix in 727f93f8ea3dc467694d541d28ba4f1ed0e0a671 for a similar type of issue with cms_common.c, but I was unable to apply the same kind of fix without getting some new errors :).

/usr/bin/gcc -I/ts/ports/components/pesign/work/src/pesign/include -I/usr/include/nspr -g -O0  -Wall -fshort-wchar -fno-strict-aliasing -fno-merge-constants --std=gnu99 -D_GNU_SOURCE -Wno-unused-result -Wno-unused-function -I../include/  -I/usr/include/nss  -Werror -fPIE -DCONFIG_ia32 -c efisiglist.c -o efisiglist.o
efisiglist.c:41:3: error: initialization discards 'const' qualifier from pointer target type [-Werror]
   .guid = &efi_guid_sha256,
   ^
efisiglist.c:45:3: error: initialization discards 'const' qualifier from pointer target type [-Werror]
   .guid = &efi_guid_sha1,
   ^
cc1: all warnings being treated as errors
/ts/ports/components/pesign/work/src/pesign/Make.rules:11: recipe for target 'efisiglist.o' failed
make[1]: *** [efisiglist.o] Error 1
make[1]: Leaving directory '/ts/ports/components/pesign/work/src/pesign/src'
Makefile:12: recipe for target 'src' failed
make: *** [src] Error 2

**Comment by vathpela** [comment]
Hey, does this work better for you with ac9de61 ?

**Comment by vathpela** [comment]
I'm going to assume it does work better now; feel free to re-open if it's not fixed and you have more data.
