### ISSUE TITLE
build fails with undefined reference to symbol pthread_rwlock_rwlock

### ISSUE THREAD

**Issue by grawity** [rhinstaller/pesign#18]
Continuing from #15 since non-contributors cannot reopen a closed task and the thing still doesn't build. As mentioned in the last comment,

> libdpe _is_ using the function the linker is complaining about; see the calls to rwlock_wrlock() which are translated via preprocessor defines to pthread_rwlock_wrlock().

Indeed, `libdpe/lock.h` has this:

```
#define RWLOCK_CALL(call) \
	({ int _err = pthread_rwlock_ ## call; assert_perror(_err); })
[...]
#define rwlock_wrlock(lock)	RWLOCK_CALL(wrlock (&lock))
```

So it very much looks like pesign is trying to use the function directly, and so should -lpthread directly.

And yes, I see that libdpe/Makefile has `LIBS=pthread`. That seems to work fine for the shared library (libdpe.so), but pesign itself uses the static library (libdpe.a) and I don't believe static libs even have a place to record this kind of information?

**Comment by vathpela** [comment]
Fixed in 0.112, thanks.
